Feature/n+1
yigitm/blogger pull request #7
Opened 2022-04-01 23:31 UTC by yigitm

In this PR:

- Validations are added for the User model
- Unit tests are added for methods and validations
- Flash messages are added to 'create' actions
- The N+1 problem is fixed on the user post  page

Thank you for your time.

2022-04-01 23:50 UTC, hiromataba requested changes
Hi @yigitm      :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Nice commit history :heavy_check_mark: 

## Required Changes ♻️

- [ ] Please add information in your  README file on how to get and run your project locally 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 23:50 UTC, hiromataba commented on spec/models/post_spec.rb
> +  user = User.create(name: 'Test User',
- [ ] When I am trying to run the tests  I am getting the error below :point_down:  please fix that because it is preventing all your tests from running

![image](https://user-images.githubusercontent.com/75126481/161355094-81ddc381-d303-4f09-b017-a19ae660d165.png)

2022-04-02 00:59 UTC, merged

2022-04-02 01:04 UTC, yigitm commented on spec/models/post_spec.rb
> +  user = User.create(name: 'Test User',
thank you for that. I had a problem with vs code auto-commit. Try to fix it.

2022-04-02 01:04 UTC, yigitm commented on spec/models/post_spec.rb
> +  user = User.create(name: 'Test User',
It did not issued my latest commits including readme updates.